# -*- coding: utf-8 -*-
"""jp morgan task 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zkc6RhPbInH3NsYGTBEvXVC7V8Iz9R01
"""

